# fly.toml app configuration file generated for podly on 2024-10-04T15:03:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'podly'
primary_region = 'mad'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'podly.fly.dev'
  PORT = '8080'
  FLY_IO = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
  memory = 512
